const RAW_INITIAL_ARTWORKS = [
  {
    id: 'art-echo-101',
    title: 'The Golden Crown of Benin (Echo of Eternity)',
    artistName: 'Ebuka Eke Echo',
    artistId: 'artist-ebuka-eke',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Paintings',
    medium: 'Oil & 24K Gold Leaf on Linen Canvas',
    dimensions: '160 x 130 cm',
    price: 2800000,
    priceUSD: 1890,
    status: 'available',
    year: '2026',
    provenance: 'Created in Lagos Atelier by Master Artist Ebuka Eke Echo. Verified Dual Certificate Registry.',
    description: 'An evocative masterpiece exploring royal heritage, resilience, and Pan-African sovereignty through deep indigo hues, earth pigments, and radiant 24k gold leaf gilding.',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 28,
    isNewlyListed: true,
    isFeatured: true,
    isDemo: false,
    created_at: '2026-08-31T10:00:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America', 'Middle East', 'Asia'],
    verificationBadge: 'gold',
    studioNotes: 'Every brushstroke is infused with reverence for ancestral memory. Gold leaf is carefully laid by hand in quiet devotion to authentic African excellence.'
  },
  {
    id: 'art-101',
    title: 'The Ancestral Horizon',
    artistName: 'Kofi Mensah',
    artistId: 'artist-1',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Oil & Gold Leaf on Canvas',
    dimensions: '150 x 120 cm',
    price: 1850000, // ₦1.85m
    priceUSD: 1250,
    status: 'available', // available, sold, upcoming, auction
    year: '2025',
    provenance: 'Created in Accra, Ghana. Exhibited at 2025 Contemporary African Art Biennale.',
    description: 'A breathtaking exploration of West African royal lineage, utilizing 24k gold leaf layerings and deep indigo acrylics to capture the eternal spirit of ancestral wisdom.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 18,
    isNewlyListed: true,
    isFeatured: true,
    created_at: '2026-02-10T10:00:00Z',
    country: 'Ghana',
    city: 'Accra',
    countryFlag: '🇬🇭',
    shipsTo: ['Africa', 'Europe', 'North America', 'Middle East'],
    verificationBadge: 'gold',
    studioNotes: 'My studio in Accra is filled with ancestral masks and bowls of gold dust. Every morning I grind pigment by hand — a ritual my grandfather taught me. The gold leaf is applied last, always in silence, as an offering to those who came before us.',
  },
  {
    id: 'art-102',
    title: 'Warrior of the Bronze Empire',
    artistName: 'Amina Diallo',
    artistId: 'artist-2',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Cast Bronze & Ebony Wood Base',
    dimensions: '85 x 40 x 35 cm',
    price: 3200000, // ₦3.2m
    priceUSD: 2150,
    status: 'auction',
    year: '2026',
    provenance: 'Hand-sculpted using ancient lost-wax technique in Benin City.',
    description: 'An intricate bronze bust representing royal Benin warriors, balancing historical reverence with bold modern geometry.',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 32,
    isNewlyListed: false,
    isFeatured: true,
    auction: {
      startingBid: 2500000,
      currentBid: 3400000,
      totalBids: 14,
      endTime: new Date(Date.now() + 1000 * 60 * 60 * 28).toISOString(), // 28 hrs from now
    },
    created_at: '2026-02-08T12:00:00Z',
    country: 'Nigeria',
    city: 'Benin City',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America', 'Asia', 'Middle East'],
    verificationBadge: 'heritage',
    studioNotes: 'I work beside the same foundry fire my great-grandmother lit. The lost-wax method is not a technique to me — it is a language. Bronze holds memory in ways canvas cannot.',
  },
  {
    id: 'art-103',
    title: 'Echoes of the Serengeti',
    artistName: 'Tariq Ndebele',
    artistId: 'artist-3',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Mixed Media & Natural Pigments',
    dimensions: '180 x 100 cm',
    price: 950000, // ₦950k
    priceUSD: 640,
    status: 'sold',
    year: '2025',
    provenance: 'Private collection, Johannesburg, South Africa.',
    description: 'Rich earth pigments harvested from Kwazulu-Natal rendered into sweeping savannah landscapes reflecting migratory memory.',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 12,
    soldTo: 'Dr. O. Adebayo (Lagos)',
    soldPrice: 1100000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-15T09:00:00Z',
    country: 'South Africa',
    city: 'Johannesburg',
    countryFlag: '🇿🇦',
    shipsTo: ['Africa', 'Europe'],
    verificationBadge: 'verified',
    studioNotes: 'I collect soil, ash, and plant matter from across southern Africa and grind them into pigment. There is no synthetic colour in my studio — only the continent itself, translated onto canvas.',
  },
  {
    id: 'art-104',
    title: 'The Solitary Mask of Oyo',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Carved Iroko Wood & Brass Inlay',
    dimensions: '90 x 35 x 25 cm',
    price: 1450000,
    priceUSD: 980,
    status: 'available',
    year: '2026',
    provenance: 'Master carver studio in Oyo State, Nigeria.',
    description: 'Sacred Yoruba ceremonial ceremonial carving infused with modern minimalist contours and hand-hammered brass inlay.',
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 21,
    isNewlyListed: true,
    isFeatured: true,
    created_at: '2026-02-12T15:30:00Z',
    country: 'Nigeria',
    city: 'Oyo',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. The chisel speaks its own dialect. My studio is a sacred compound — visitors remove their shoes.',
  },
  {
    id: 'art-105',
    title: 'Quantum Afrofuturism No. 7',
    artistName: 'Zola Okafor',
    artistId: 'artist-5',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: '3D Render & Fine Art Giclée Print',
    dimensions: '100 x 100 cm (Edition 1 of 5)',
    price: 750000,
    priceUSD: 500,
    status: 'upcoming',
    year: '2026',
    provenance: 'Digital release scheduled for Lagos Art Week 2026.',
    description: 'Surrealist digital vision blending traditional Nsibidi ideograms with futuristic cyberpunk neon architecture.',
    image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviewsCount: 9,
    isNewlyListed: false,
    isFeatured: false,
    releaseDate: '2026-03-01T00:00:00Z',
    created_at: '2026-02-14T08:00:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Worldwide'],
    verificationBadge: 'verified',
    studioNotes: 'I render in the dark — literally. My setup is three monitors and a drawing tablet in a blacked-out room. Nsibidi symbols are my building blocks.',
  },
  {
    id: 'art-106',
    title: 'Daughters of the Nile',
    artistName: 'Nour El-Din',
    artistId: 'artist-6',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Oil on Lined Canvas',
    dimensions: '200 x 140 cm',
    price: 4500000, // ₦4.5m
    priceUSD: 3000,
    status: 'auction',
    year: '2025',
    provenance: 'Cairo Fine Arts Gallery exhibition piece.',
    description: 'Monumental portrait paying homage to Nubian queens and North African textile heritage.',
    image: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 45,
    isNewlyListed: false,
    isFeatured: true,
    auction: {
      startingBid: 3800000,
      currentBid: 4800000,
      totalBids: 22,
      endTime: new Date(Date.now() + 1000 * 60 * 60 * 52).toISOString(),
    },
    created_at: '2026-01-20T10:00:00Z',
    country: 'Egypt',
    city: 'Cairo',
    countryFlag: '🇪🇬',
    shipsTo: ['Africa', 'Europe', 'Middle East', 'North America'],
    verificationBadge: 'heritage',
    studioNotes: 'My studio overlooks the Nile. I spend hours just watching the light change on the water before I pick up a brush.',
  },
  {
    id: 'art-107',
    title: 'Spirit of the Mask',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Carved Mahogany Wood',
    dimensions: '110 x 40 x 30 cm',
    price: 1950000,
    priceUSD: 1320,
    status: 'available',
    year: '2026',
    provenance: 'Sacred carving compound in Oyo, Nigeria.',
    description: 'A striking mahogany mask balancing ritual geometric carving with modern sleek visual accents.',
    image: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 15,
    isNewlyListed: true,
    isFeatured: true,
    created_at: '2026-02-13T09:00:00Z',
    country: 'Nigeria',
    city: 'Oyo',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. The chisel speaks its own dialect. My studio is a sacred compound — visitors remove their shoes.',
  },
  {
    id: 'art-108',
    title: 'The Golden Benin Queen',
    artistName: 'Amina Diallo',
    artistId: 'artist-2',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Polished Bronze and Gold Filigree',
    dimensions: '95 x 45 x 40 cm',
    price: 4800000,
    priceUSD: 3250,
    status: 'auction',
    year: '2026',
    provenance: 'Benin City lost-wax sculpture foundry.',
    description: 'Regal bronze bust of Benin royalty layered with fine gold filigree design patterns.',
    image: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 28,
    isNewlyListed: true,
    isFeatured: true,
    auction: {
      startingBid: 4000000,
      currentBid: 4900000,
      totalBids: 19,
      endTime: new Date(Date.now() + 1000 * 60 * 60 * 15).toISOString(),
    },
    created_at: '2026-02-11T14:30:00Z',
    country: 'Nigeria',
    city: 'Benin City',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America', 'Asia', 'Middle East'],
    verificationBadge: 'heritage',
    studioNotes: 'I work beside the same foundry fire my great-grandmother lit. The lost-wax method is not a technique to me — it is a language.',
  },
  {
    id: 'art-109',
    title: 'Children of the Sun',
    artistName: 'Kenza Belghiti',
    artistId: 'artist-7',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Acrylic and Gold Leaf on Linen',
    dimensions: '160 x 130 cm',
    price: 2100000,
    priceUSD: 1420,
    status: 'available',
    year: '2025',
    provenance: 'Exhibited at Casablanca Gallery of Fine Arts.',
    description: 'Vibrant representation of North African youth set against bright golden solar rays.',
    image: 'https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 14,
    isNewlyListed: true,
    isFeatured: false,
    created_at: '2026-02-05T11:00:00Z',
    country: 'Morocco',
    city: 'Casablanca',
    countryFlag: '🇲🇦',
    shipsTo: ['Africa', 'Europe'],
    verificationBadge: 'verified',
    studioNotes: 'My studio sits in the old medina quarter. The light through the zellige tile windows is unlike anything else in the world.',
  },
  {
    id: 'art-110',
    title: 'Ancestral Geometry',
    artistName: 'Chidi Nwosu',
    artistId: 'artist-8',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: 'Vector Graphics & Giclée Canvas Print',
    dimensions: '120 x 120 cm (Edition 2 of 10)',
    price: 620000,
    priceUSD: 420,
    status: 'available',
    year: '2026',
    provenance: 'Released for the Pan-African Digital Art Fair.',
    description: 'Intricate digital study using traditional Igbo Uli patterns mapped into geometric arrays.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviewsCount: 11,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-02-09T08:00:00Z',
    country: 'Nigeria',
    city: 'Enugu',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'verified',
    studioNotes: 'I grew up watching my grandmother draw Uli patterns on her arms for festivals. I now code those same patterns using vector mathematics.',
  },
  {
    id: 'art-111',
    title: 'Lost Kingdoms of Axum',
    artistName: 'Tariq Ndebele',
    artistId: 'artist-3',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Tempera and Charcoal on Wood panel',
    dimensions: '140 x 100 cm',
    price: 1550000,
    priceUSD: 1050,
    status: 'auction',
    year: '2026',
    provenance: 'Addis Ababa historical art archive study.',
    description: 'An architectural study of historic Axumite obelisks rendered in rich volcanic soot and charcoal.',
    image: 'https://images.unsplash.com/photo-1547891654-e66ed7edd96c?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 8,
    isNewlyListed: false,
    isFeatured: true,
    auction: {
      startingBid: 1200000,
      currentBid: 1600000,
      totalBids: 8,
      endTime: new Date(Date.now() + 1000 * 60 * 60 * 34).toISOString(),
    },
    created_at: '2026-02-02T10:00:00Z',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    countryFlag: '🇪🇹',
    shipsTo: ['Africa', 'Europe'],
    verificationBadge: 'verified',
    studioNotes: 'I collect soil, ash, and plant matter from across southern Africa and grind them into pigment.',
  },
  {
    id: 'art-112',
    title: 'Sahara Mirage',
    artistName: 'Fatoumata Diabaté',
    artistId: 'artist-9',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Sand, Oil, and Resin on Canvas',
    dimensions: '170 x 140 cm',
    price: 2800000,
    priceUSD: 1900,
    status: 'available',
    year: '2025',
    provenance: 'Created in Bamako, Mali. Private collection display.',
    description: 'Textured Malian sands blended into desert landscape forms depicting nomadic routes.',
    image: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 16,
    isNewlyListed: true,
    isFeatured: false,
    created_at: '2026-02-04T12:00:00Z',
    country: 'Mali',
    city: 'Bamako',
    countryFlag: '🇲🇱',
    shipsTo: ['Africa', 'Europe', 'Middle East'],
    verificationBadge: 'heritage',
    studioNotes: 'I gather sand from different desert regions and mix them with linseed oil and resin to create texture. The Sahara is not empty — it breathes, shifts, and tells stories.',
  },
  {
    id: 'art-113',
    title: 'Djembe Pulse',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Carved Cedarwood & Goatskin',
    dimensions: '75 x 38 x 38 cm',
    price: 1200000,
    priceUSD: 810,
    status: 'sold',
    year: '2025',
    provenance: 'Sold at West African Beats Gala.',
    description: 'A hand-carved ceremonial drum displaying intricate geometric relief carvings along its shell.',
    image: 'https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 19,
    soldTo: 'Dr. Evelyn Carter',
    soldPrice: 1200000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-25T16:00:00Z',
    country: 'Nigeria',
    city: 'Oyo',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. The chisel speaks its own dialect.',
  },
  {
    id: 'art-114',
    title: 'Future Rhythm',
    artistName: 'Zola Okafor',
    artistId: 'artist-5',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: 'Generative AI & Digital Collage Print',
    dimensions: '110 x 110 cm',
    price: 850000,
    priceUSD: 570,
    status: 'upcoming',
    year: '2026',
    provenance: 'To be released at Lagos Digital Week.',
    description: 'Digital collage depicting afrofuturistic soundscapes and vibrant neon music elements.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 7,
    releaseDate: '2026-03-15T00:00:00Z',
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-02-14T09:00:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Worldwide'],
    verificationBadge: 'verified',
    studioNotes: 'I render in the dark — literally. Nsibidi symbols are my building blocks.',
  },
  {
    id: 'art-115',
    title: 'Dynasty of Oyo',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Iroko Wood & Glass Beads',
    dimensions: '120 x 50 x 45 cm',
    price: 3500000,
    priceUSD: 2360,
    status: 'auction',
    year: '2026',
    provenance: 'Oyo State Royal Palace Guild collection.',
    description: 'Regal carving of a seated Oyo king, finished in hand-sewn historical Yoruba beadwork.',
    image: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 30,
    isNewlyListed: true,
    auction: {
      startingBid: 3000000,
      currentBid: 3650000,
      totalBids: 15,
      endTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    },
    created_at: '2026-02-12T10:00:00Z',
    country: 'Nigeria',
    city: 'Oyo',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. The chisel speaks its own dialect.',
  },
  {
    id: 'art-116',
    title: 'Memories of the Savannah',
    artistName: 'Tariq Ndebele',
    artistId: 'artist-3',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Oil and Natural Earth Pigments on Canvas',
    dimensions: '170 x 140 cm',
    price: 1700000,
    priceUSD: 1150,
    status: 'sold',
    year: '2025',
    provenance: 'Private collection, Cape Town, South Africa.',
    description: 'A beautiful abstract canvas rendered in rich ochre and sienna earth pigments depicting the South African interior.',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 15,
    soldTo: 'Lady Victoria Rothschild (London)',
    soldPrice: 1700000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-25T11:00:00Z',
    country: 'South Africa',
    city: 'Cape Town',
    countryFlag: '🇿🇦',
    shipsTo: ['Africa', 'Europe'],
    verificationBadge: 'verified',
    studioNotes: 'I collect soil, ash, and plant matter from across southern Africa and grind them into pigment.',
  },
  {
    id: 'art-117',
    title: 'Yoruba Queen Mother',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Carved Mahogany Wood, Cowrie Shells & Beads',
    dimensions: '110 x 45 x 40 cm',
    price: 2300000,
    priceUSD: 1550,
    status: 'sold',
    year: '2025',
    provenance: 'Exhibited at the Nigerian National Museum, Lagos.',
    description: 'A majestic wood carving adorned with authentic trade beads and cowrie shells, representing maternal lineage.',
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 22,
    soldTo: 'Dr. Evelyn Carter (New York)',
    soldPrice: 2300000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-28T14:30:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. The chisel speaks its own dialect.',
  },
  {
    id: 'art-118',
    title: 'Neon Nsibidi Collage',
    artistName: 'Zola Okafor',
    artistId: 'artist-5',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: 'Digital Fine Art Giclée Print',
    dimensions: '110 x 110 cm',
    price: 890000,
    priceUSD: 600,
    status: 'sold',
    year: '2025',
    provenance: 'Lagos Digital Art Fair 2025 closing ledger.',
    description: 'A bold digital composition combining ancient Nsibidi scripts with vibrant neon cyber architecture.',
    image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 7,
    soldTo: 'Abebe Selassie (Addis Ababa)',
    soldPrice: 890000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-10T09:00:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Worldwide'],
    verificationBadge: 'verified',
    studioNotes: 'I render in the dark — literally. Nsibidi symbols are my building blocks.',
  },
  {
    id: 'art-119',
    title: 'Sahara Caravan',
    artistName: 'Fatoumata Diabaté',
    artistId: 'artist-9',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Mixed Media & Malian Desert Sands',
    dimensions: '180 x 130 cm',
    price: 3100000,
    priceUSD: 2100,
    status: 'sold',
    year: '2025',
    provenance: 'Collection of the Curatorial Society, Paris.',
    description: 'Textured Malian sands combined with oil paints, capturing the quiet majesty of a Sahara desert crossing.',
    image: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 18,
    soldTo: 'Jean-Pierre Dubois (Paris)',
    soldPrice: 3100000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-12T10:00:00Z',
    country: 'Mali',
    city: 'Bamako',
    countryFlag: '🇲🇱',
    shipsTo: ['Africa', 'Europe', 'Middle East'],
    verificationBadge: 'heritage',
    studioNotes: 'I gather sand from different desert regions and mix them with linseed oil and resin.',
  },
  {
    id: 'art-120',
    title: 'Whispering Winds of the Savannah',
    artistName: 'Kenza Belghiti',
    artistId: 'artist-7',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Mixed Media on Canvas',
    dimensions: '150 x 120 cm',
    price: 1500000,
    priceUSD: 1010,
    status: 'available',
    year: '2025',
    provenance: 'Exhibited at Casablanca Contemporary Gallery.',
    description: 'A textured canvas capturing the warm movement of wind across dry savannah grass.',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 12,
    isNewlyListed: true,
    isFeatured: false,
    created_at: '2026-02-06T10:00:00Z',
    country: 'Morocco',
    city: 'Casablanca',
    countryFlag: '🇲🇦',
    shipsTo: ['Africa', 'Europe'],
    verificationBadge: 'verified',
    studioNotes: 'My studio sits in the old medina quarter. The light through the zellige tile windows is unlike anything else.',
  },
  {
    id: 'art-121',
    title: 'Rivers of the Great Rift',
    artistName: 'Nour El-Din',
    artistId: 'artist-6',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Oil on Raw Linen',
    dimensions: '165 x 130 cm',
    price: 2650000,
    priceUSD: 1790,
    status: 'available',
    year: '2026',
    provenance: 'Cairo Studio. Featured at the East African Arts Council Summit.',
    description: "Sweeping oil panorama of the Great Rift Valley's ancient waterways rendered in lapis lazuli and raw sienna pigments.",
    image: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 17,
    isNewlyListed: true,
    isFeatured: true,
    created_at: '2026-02-16T10:00:00Z',
    country: 'Egypt',
    city: 'Cairo',
    countryFlag: '🇪🇬',
    shipsTo: ['Africa', 'Europe', 'Middle East', 'North America'],
    verificationBadge: 'heritage',
    studioNotes: 'My studio overlooks the Nile. I spend hours just watching the light change on the water before I pick up a brush.',
  },
  {
    id: 'art-122',
    title: "The Griot's Lament",
    artistName: 'Kofi Mensah',
    artistId: 'artist-1',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Acrylic & Charcoal on Canvas',
    dimensions: '140 x 110 cm',
    price: 1950000,
    priceUSD: 1315,
    status: 'available',
    year: '2026',
    provenance: 'Accra Contemporary Arts Collective.',
    description: "A haunting portrait of a West African griot preserving oral traditions under the weight of modernity.",
    image: 'https://images.unsplash.com/photo-1551913902-c92207136625?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 10,
    isNewlyListed: true,
    isFeatured: false,
    created_at: '2026-02-17T08:00:00Z',
    country: 'Ghana',
    city: 'Accra',
    countryFlag: '🇬🇭',
    shipsTo: ['Africa', 'Europe', 'North America', 'Middle East'],
    verificationBadge: 'gold',
    studioNotes: 'My studio in Accra is filled with ancestral masks and bowls of gold dust. Every morning I grind pigment by hand.',
  },
  {
    id: 'art-123',
    title: 'Totem of the Lake Victoria Basin',
    artistName: 'Chidi Nwosu',
    artistId: 'artist-8',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: 'Augmented Reality Digital Print',
    dimensions: '100 x 100 cm (Edition 3 of 10)',
    price: 720000,
    priceUSD: 485,
    status: 'available',
    year: '2026',
    provenance: 'Released at the Nairobi Digital Futures Summit.',
    description: 'Ceremonial digital totem blending East African tribal iconography with glitched cyber-aesthetic detail.',
    image: 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviewsCount: 6,
    isNewlyListed: true,
    isFeatured: false,
    created_at: '2026-02-18T09:00:00Z',
    country: 'Nigeria',
    city: 'Enugu',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'verified',
    studioNotes: 'I grew up watching my grandmother draw Uli patterns on her arms for festivals. Tradition does not die — it migrates into new tools.',
  },
  {
    id: 'art-124',
    title: 'Throne of Kush',
    artistName: 'Kofi Mensah',
    artistId: 'artist-1',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    category: 'Painters',
    medium: 'Oil & Gold Foil on Canvas',
    dimensions: '200 x 160 cm',
    price: 3800000,
    priceUSD: 2565,
    status: 'sold',
    year: '2025',
    provenance: 'Sold at the Accra Biennale Private Sale.',
    description: 'A regal, monumental canvas depicting the throne hall of an ancient Nubian Kushite pharaoh draped in symbolic gold.',
    image: 'https://images.unsplash.com/photo-1588420343618-6141b3784bce?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviewsCount: 26,
    soldTo: 'Sheikh Rashed Al-Farsi (Dubai)',
    soldPrice: 4200000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-05T10:00:00Z',
    country: 'Ghana',
    city: 'Accra',
    countryFlag: '🇬🇭',
    shipsTo: ['Africa', 'Europe', 'North America', 'Middle East'],
    verificationBadge: 'gold',
    studioNotes: 'My studio in Accra is filled with ancestral masks and bowls of gold dust. The gold leaf is applied last, always in silence.',
  },
  {
    id: 'art-125',
    title: 'Mask of the Poro Society',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    artistType: 'Premium',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    category: 'Sculpture Makers',
    medium: 'Polychrome Carved Hardwood & Pigment',
    dimensions: '80 x 30 x 22 cm',
    price: 2100000,
    priceUSD: 1415,
    status: 'sold',
    year: '2025',
    provenance: 'Ceremonial gallery, Abidjan, Côte d\'Ivoire.',
    description: 'A vibrant ritual mask from the Poro secret society tradition, painted with organic red and white pigments.',
    image: 'https://images.unsplash.com/photo-1574534003964-e90e2ae62e70?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviewsCount: 20,
    soldTo: 'Musée du quai Branly (Paris)',
    soldPrice: 2500000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-18T13:00:00Z',
    country: 'Nigeria',
    city: 'Oyo',
    countryFlag: '🇳🇬',
    shipsTo: ['Africa', 'Europe', 'North America'],
    verificationBadge: 'gold',
    studioNotes: 'I was initiated into carving by my father at age nine. My studio is a sacred compound — visitors remove their shoes.',
  },
  {
    id: 'art-126',
    title: 'Digital Griot Series I',
    artistName: 'Zola Okafor',
    artistId: 'artist-5',
    artistType: 'Standard',
    artistAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    category: 'Digital Art',
    medium: 'Generative AI & Archival Pigment Print',
    dimensions: '120 x 120 cm (Edition 1 of 5)',
    price: 1100000,
    priceUSD: 740,
    status: 'sold',
    year: '2025',
    provenance: 'Lagos Art Week 2025 Digital Sale.',
    description: 'First edition in a generative series exploring the digital transmission of African oral traditions.',
    image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviewsCount: 13,
    soldTo: 'Dr. Funmi Adeyemi (Lagos)',
    soldPrice: 1350000,
    isNewlyListed: false,
    isFeatured: false,
    created_at: '2026-01-22T15:00:00Z',
    country: 'Nigeria',
    city: 'Lagos',
    countryFlag: '🇳🇬',
    shipsTo: ['Worldwide'],
    verificationBadge: 'verified',
    studioNotes: 'I render in the dark — literally. Nsibidi symbols are my building blocks. Each glyph is a pixel of cultural memory.',
  },
];

export const INITIAL_ARTWORKS = RAW_INITIAL_ARTWORKS.map((art) => ({
  ...art,
  isDemo: art.isDemo === false ? false : true,
  created_at: art.isDemo === false 
    ? (art.created_at || new Date().toISOString())
    : (art.created_at || '2025-10-01T00:00:00Z')
        .replace('2026-02', '2025-11')
        .replace('2026-01', '2025-10')
}));

export const ARTIST_VIDEOS = [
  {
    id: 'vid-1',
    artistName: 'Kofi Mensah',
    artistTitle: 'Master Painter & Gold Leaf Specialist',
    country: 'Ghana',
    artworkTitle: 'The Ancestral Horizon',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Sample embed URL
    quote: "Every stroke of gold leaf represents a prayer for our forebears who paved the path for global African creative dominance.",
    duration: '3:45',
  },
  {
    id: 'vid-2',
    artistName: 'Amina Diallo',
    artistTitle: 'Bronze Sculptor & Heritage Preserver',
    country: 'Nigeria',
    artworkTitle: 'Warrior of the Bronze Empire',
    thumbnail: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    quote: "Working with molten bronze requires total spiritual connection. We are breathing new life into 500-year-old foundry traditions.",
    duration: '4:20',
  },
  {
    id: 'vid-3',
    artistName: 'Chief Bakare Ogundele',
    artistTitle: 'Master Wood Carver',
    country: 'Nigeria',
    artworkTitle: 'The Solitary Mask of Oyo',
    thumbnail: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    quote: "The wood speaks to the chisel long before the shape emerges. ARTELLIUM gives our sacred art a global voice.",
    duration: '2:50',
  },
];

export const VIRTUAL_EXHIBITIONS = [
  {
    id: 'ex-101',
    slug: 'dynasties-of-the-niger',
    title: 'Dynasties of the Niger: Benin Bronze & Sacred Timber',
    timingCategory: 'current', // 'current', 'upcoming', 'past', 'virtual'
    format: 'Physical exhibitions',
    formatLabel: 'Physical Exhibition',
    location: 'National Museum Pavilion, Lagos, Nigeria',
    accessibleCities: ['Lagos', 'Abuja', 'London', 'New York'],
    sdgDiscussion: 'SDG 11: Sustainable Cities & Cultural Heritage Preservation',
    sdgTag: 'SDG 11',
    curator: 'Dr. Farai Mutambara',
    curatorTitle: 'Senior Curator of Pan-African Antiquities',
    curatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'Dynasties of the Niger stands as a profound inquiry into the metallurgical mastery and sacred woodcraft of the Niger Basin kingdoms. By uniting ancestral lost-wax bronze castings with sustainably harvested sacred timbers, this exhibition demonstrates how ancient African craft ecosystems established timeless models of environmental stewardship long before contemporary sustainability frameworks.',
    status: 'Live Now',
    startDate: 'Feb 1, 2026',
    endDate: 'Mar 30, 2026',
    openingHours: 'Tuesday – Sunday: 10:00 AM – 7:00 PM WAT',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 24,
    participatingArtists: [
      { name: 'Amina Diallo', role: 'Royal Bronze Sculptor', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300' },
      { name: 'Chief Bakare Ogundele', role: 'Master Wood Carver', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300' },
      { name: 'Kofi Mensah', role: '24K Gold Leaf Painter', country: 'Ghana 🇬🇭', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-102', title: 'Warrior of the Bronze Empire', artist: 'Amina Diallo', medium: 'Cast Bronze & Ebony', dimensions: '85 × 40 × 35 cm', price: 3200000, image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-108', title: 'The Golden Benin Queen', artist: 'Amina Diallo', medium: 'Polished Bronze & Gold Filigree', dimensions: '95 × 45 × 40 cm', price: 4800000, image: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-104', title: 'The Solitary Mask of Oyo', artist: 'Chief Bakare Ogundele', medium: 'Carved Iroko Wood & Brass', dimensions: '90 × 35 × 25 cm', price: 1450000, image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-101', title: 'The Ancestral Horizon', artist: 'Kofi Mensah', medium: 'Oil & Gold Leaf on Canvas', dimensions: '150 × 120 cm', price: 1850000, image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'A physical landmark museum exhibition examining the monumental heritage of West African bronze foundry casting, sacred timber carving, and indigenous sustainability practices.',
  },
  {
    id: 'ex-102',
    slug: 'pan-african-3d-spatial',
    title: 'Pan-African 3D Spatial Continuum',
    timingCategory: 'virtual',
    format: 'Virtual exhibitions',
    formatLabel: '3D Virtual Exhibition Room',
    location: 'Interactive 3D WebGL Spatial Gallery (Global Access: Lagos • Abuja • London • New York)',
    accessibleCities: ['Abuja', 'Lagos', 'London', 'New York', 'Worldwide'],
    sdgDiscussion: 'SDG 9: Industry, Innovation & Digital Infrastructure in Fine Art',
    sdgTag: 'SDG 9',
    curator: 'Zola Okafor',
    curatorTitle: 'Digital Fine Art Fellow & Spatial Curator',
    curatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'The 3D Spatial Continuum dismantles geographical barriers between African creators and global collectors. Whether stepping in from an office in London, an apartment in Manhattan, or a salon in Abuja and Lagos, visitors explore ultra-high resolution masterworks in a physics-simulated architectural gallery space.',
    status: 'Live Now',
    startDate: 'Jan 15, 2026',
    endDate: 'Ongoing (24/7 Global Immersion)',
    openingHours: 'Always Open (24/7 WebGL 3D Immersion)',
    coverImage: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 18,
    participatingArtists: [
      { name: 'Zola Okafor', role: 'Afrofuturist 3D Creator', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300' },
      { name: 'Chidi Nwosu', role: 'Geometric Visualist', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300' },
      { name: 'Nour El-Din', role: 'Monumental Colorist', country: 'Egypt 🇪🇬', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-105', title: 'Quantum Afrofuturism No. 7', artist: 'Zola Okafor', medium: '3D Render & Fine Art Giclée', dimensions: '100 × 100 cm', price: 750000, image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-110', title: 'Ancestral Geometry', artist: 'Chidi Nwosu', medium: 'Vector Uli Graphics on Canvas', dimensions: '120 × 120 cm', price: 620000, image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-106', title: 'Daughters of the Nile', artist: 'Nour El-Din', medium: 'Oil on Lined Canvas', dimensions: '200 × 140 cm', price: 4500000, image: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'An interactive virtual museum journey connecting global collectors with certified African master painters, sculptors, and digital creators worldwide.',
  },
  {
    id: 'ex-103',
    slug: 'earth-pigments-salon',
    title: 'Earth Pigments & Sustainable Living Salon',
    timingCategory: 'current',
    format: 'Pop-up galleries',
    formatLabel: 'Pop-Up Gallery',
    location: 'Victoria Island Curatorial Lounge, Lagos (Virtual Access Global)',
    accessibleCities: ['Lagos', 'Abuja', 'London', 'New York'],
    sdgDiscussion: 'SDG 12: Responsible Consumption & Eco-Friendly Raw Earth Pigments',
    sdgTag: 'SDG 12',
    curator: 'Tariq Ndebele & Amina Diallo',
    curatorTitle: 'Eco-Art Practitioners & Curators',
    curatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'Earth Pigments & Sustainable Living explores the tactile dialogue between African mineral soils, botanical vegetable tinctures, and contemporary easel practice. By rejecting toxic synthetic acrylics in favor of hand-ground ochres and Kwazulu-Natal clays, our artists lead a renaissance in regenerative fine art creation.',
    status: 'Live Now',
    startDate: 'Feb 10, 2026',
    endDate: 'Apr 10, 2026',
    openingHours: 'Wednesday – Sunday: 11:00 AM – 8:00 PM WAT',
    coverImage: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 14,
    participatingArtists: [
      { name: 'Tariq Ndebele', role: 'Earth Pigment Painter', country: 'South Africa 🇿🇦', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300' },
      { name: 'Fatoumata Diabaté', role: 'Desert Sand Master', country: 'Mali 🇲🇱', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-103', title: 'Echoes of the Serengeti', artist: 'Tariq Ndebele', medium: 'Raw Earth Pigments & Ash on Linen', dimensions: '180 × 100 cm', price: 950000, image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-112', title: 'Sahara Mirage', artist: 'Fatoumata Diabaté', medium: 'Malian Desert Sands & Resin', dimensions: '170 × 140 cm', price: 2800000, image: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'An intimate pop-up gallery and curatorial salon hosting live discussions on zero-waste art creation, natural vegetable dyes, and sustainable living through traditional arts.',
  },
  {
    id: 'ex-104',
    slug: 'diaspora-biennale-london-paris',
    title: 'African Master Creators: London & Paris Diaspora Biennale',
    timingCategory: 'upcoming',
    format: 'International showcases',
    formatLabel: 'International Showcase',
    location: 'Grand Palais Diaspora Pavilion, Paris & London (Global 3D Simulcast)',
    accessibleCities: ['London', 'Paris', 'New York', 'Lagos', 'Abuja'],
    sdgDiscussion: 'SDG 8 & 17: Decent Work, Economic Empowerment & Global Partnerships',
    sdgTag: 'SDG 8 & 17',
    curator: 'Dr. Evelyn Carter',
    curatorTitle: 'Chief International Curator, Artellium Africa',
    curatorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'The Diaspora Biennale establishes an institutional corridor connecting contemporary African master ateliers directly with global museums, private foundation vaults, and sovereign art trusts. Our dual presentation across European capitals and digital 3D streams ensures unprecedented accessibility.',
    status: 'Upcoming',
    startDate: 'Apr 15, 2026',
    endDate: 'Jun 1, 2026',
    openingHours: 'Opening Gala: April 15, 2026 • 6:00 PM GMT',
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 30,
    participatingArtists: [
      { name: 'Kofi Mensah', role: 'Painter', country: 'Ghana 🇬🇭', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300' },
      { name: 'Amina Diallo', role: 'Sculptor', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300' },
      { name: 'Nour El-Din', role: 'Painter', country: 'Egypt 🇪🇬', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-101', title: 'The Ancestral Horizon', artist: 'Kofi Mensah', medium: 'Oil & Gold Leaf on Canvas', dimensions: '150 × 120 cm', price: 1850000, image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-106', title: 'Daughters of the Nile', artist: 'Nour El-Din', medium: 'Oil on Canvas', dimensions: '200 × 140 cm', price: 4500000, image: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'An international fine art delegation presenting authentic African masterpieces to global museum directors, institutional funds, and diplomatic patrons.',
  },
  {
    id: 'ex-105',
    slug: 'sahara-mirage-retrospective',
    title: 'Sahara Mirage: Nomadic Modernity & Desert Light',
    timingCategory: 'upcoming',
    format: 'Physical exhibitions',
    formatLabel: 'Physical & 3D Exhibition',
    location: 'Abuja International Arts Center, Abuja, Nigeria',
    accessibleCities: ['Abuja', 'Lagos', 'London', 'New York'],
    sdgDiscussion: 'SDG 15: Life on Land & Combating Desertification through Storytelling',
    sdgTag: 'SDG 15',
    curator: 'Fatoumata Diabaté & Kenza Belghiti',
    curatorTitle: 'North-West African Curatorial Circle',
    curatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'Sahara Mirage examines trans-Saharan trade routes as conduits of artistic innovation. From the clay architecture of Djenné to the mineral horizons of Timbuktu, this retrospective captures light, heat, and resilience.',
    status: 'Upcoming',
    startDate: 'May 1, 2026',
    endDate: 'Jun 20, 2026',
    openingHours: 'Opening Night: May 1, 2026',
    coverImage: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 20,
    participatingArtists: [
      { name: 'Fatoumata Diabaté', role: 'Painter', country: 'Mali 🇲🇱', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300' },
      { name: 'Kenza Belghiti', role: 'Mixed Media Artist', country: 'Morocco 🇲🇦', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-112', title: 'Sahara Mirage', artist: 'Fatoumata Diabaté', medium: 'Sand & Resin on Canvas', dimensions: '170 × 140 cm', price: 2800000, image: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-109', title: 'Children of the Sun', artist: 'Kenza Belghiti', medium: 'Acrylic & Gold Leaf', dimensions: '160 × 130 cm', price: 2100000, image: 'https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'An ambitious retrospective bringing together sand, sun, and nomadic traditions from Mali, Morocco, and Niger.',
  },
  {
    id: 'ex-106',
    slug: 'voices-of-independence',
    title: 'Voices of Independence: 1960–1980 African Fine Art Modernism',
    timingCategory: 'past',
    format: 'Physical exhibitions',
    formatLabel: 'Retrospective Exhibition Archive',
    location: 'National Arts Theatre Hall, Lagos, Nigeria (Archived)',
    accessibleCities: ['Lagos', 'London', 'New York'],
    sdgDiscussion: 'SDG 16: Peace, Justice & Strong Cultural Institutions',
    sdgTag: 'SDG 16',
    curator: 'Prof. Wole Oladipo',
    curatorTitle: 'Emeritus Curator of Modern African Art',
    curatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'Voices of Independence documented the foundational post-colonial artistic explosion that redefined African visual identity. From the Zaria Art Society rebels to Osogbo sacred art workshops, this retrospective preserves irreplaceable cultural milestones.',
    status: 'Archived / Past',
    startDate: 'Oct 1, 2025',
    endDate: 'Jan 10, 2026',
    openingHours: 'Exhibition Concluded • Archive & Catalog Available',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 45,
    participatingArtists: [
      { name: 'Kofi Mensah', role: 'Master Painter', country: 'Ghana 🇬🇭', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300' },
      { name: 'Chief Bakare Ogundele', role: 'Sculptor', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-101', title: 'The Ancestral Horizon', artist: 'Kofi Mensah', medium: 'Oil & Gold Leaf', dimensions: '150 × 120 cm', price: 1850000, image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'A historical retrospective charting the birth of modern African fine art movements following national independence.',
  },
  {
    id: 'ex-107',
    slug: 'global-virtual-pavilion',
    title: 'Global Virtual Pavilion: Masterpieces from Abuja, Lagos, London & New York',
    timingCategory: 'virtual',
    format: 'Virtual exhibitions',
    formatLabel: '3D Spatial Masterpiece Pavilion',
    location: 'Interactive Global 3D Virtual Gallery (Abuja • Lagos • London • New York)',
    accessibleCities: ['Abuja', 'Lagos', 'London', 'New York', 'Worldwide'],
    sdgDiscussion: 'SDG 11 & 17: Sustainable Cultural Heritage & Global Creative Access',
    sdgTag: 'SDG 11 & 17',
    curator: 'Artellium International Curatorial Board',
    curatorTitle: 'Pan-African & Global Curatorial Council',
    curatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    curatorStatement: 'The Global Virtual Pavilion unites masterworks from studios across Africa, providing an interactive spatial walk-through accessible seamlessly to collectors in Abuja, Lagos, London, New York, and every corner of the globe.',
    status: 'Live Now',
    startDate: 'Jan 1, 2026',
    endDate: 'Permanent 3D Display',
    openingHours: '24/7 Unlimited Virtual Access',
    coverImage: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=1200',
    featuredArtworksCount: 35,
    participatingArtists: [
      { name: 'Amina Diallo', role: 'Bronze Foundry Master', country: 'Nigeria 🇳🇬', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300' },
      { name: 'Kofi Mensah', role: 'Gold Leaf Painter', country: 'Ghana 🇬🇭', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300' },
      { name: 'Nour El-Din', role: 'Master Painter', country: 'Egypt 🇪🇬', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300' }
    ],
    exhibitedArtworks: [
      { id: 'art-108', title: 'The Golden Benin Queen', artist: 'Amina Diallo', medium: 'Polished Bronze & Gold Filigree', dimensions: '95 × 45 × 40 cm', price: 4800000, image: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=1000' },
      { id: 'art-102', title: 'Warrior of the Bronze Empire', artist: 'Amina Diallo', medium: 'Cast Bronze & Ebony', dimensions: '85 × 40 × 35 cm', price: 3200000, image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000' }
    ],
    virtualGalleryAvailable: true,
    description: 'A sovereign digital exhibition pavilion allowing art lovers in Abuja, Lagos, London, and New York to experience certified African fine art in full 3D spatial fidelity.',
  }
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'standard',
    name: 'Standard Artist',
    monthlyPrice: 30000, // ₦30,000
    yearlyPrice: 200000, // ₦200,000 (discounted)
    currency: 'NGN',
    badge: 'Standard Badge',
    features: [
      'Upload up to 15 Artworks per month',
      'Personalized Artist Profile & Bio',
      'Standard Marketplace Catalog Listing',
      'Buyer Direct Messaging & Inquiries',
      'Standard Sales Analytics Dashboard',
    ],
    recommended: false,
  },
  {
    id: 'premium',
    name: 'Premium Artist',
    monthlyPrice: 50000, // ₦50,000
    yearlyPrice: 350000, // ₦350,000 (discounted)
    currency: 'NGN',
    badge: 'Premium Verified Gold Crest',
    features: [
      'Unlimited High-Resolution Art Uploads',
      'Priority Homepage Hero Spotlight Placement',
      'Access to ARTELLIUM Live Auction Arena',
      'Pop-up Video Interview Inclusion (Admin Crated)',
      'Virtual Exhibition Gallery Solo Rooms',
      'Dedicated Curator Concierge & Global Logistics Support',
    ],
    recommended: true,
  },
];

export const CUSTOMER_REVIEWS = [
  {
    id: 'rev-1',
    artworkId: 'art-101',
    userName: 'Lord Alistair Sterling',
    location: 'London, UK',
    rating: 5,
    date: 'February 2, 2026',
    comment: 'The gold leaf detailing on "The Ancestral Horizon" is even more luminous in person. Shipped flawlessly to London with full certificate of authenticity!',
  },
  {
    id: 'rev-2',
    artworkId: 'art-102',
    userName: 'Chief Femi Alabi',
    location: 'Lagos, Nigeria',
    rating: 5,
    date: 'January 28, 2026',
    comment: 'Exceptional craftsmanship. The bronze texture carries true royal Benin dignity. Proud to display this in our family estate.',
  },
];


export const INITIAL_USERS = [
  { 
    id: 'user-admin-1', 
    name: 'Executive Administrator (Dakore Ekpendu)', 
    email: 'Ekpendudakore@gmail.com', 
    role: 'admin', 
    password: 'ladydakore@artellium90', 
    phone: '+234 800 000 0001', 
    country: 'Nigeria', 
    subscription_tier: 'premium',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-01T00:00:00Z',
    lastActive: '2026-02-22T17:00:00Z',
    cloudflareVerified: true,
    ipAddress: '102.89.22.10',
    securityIncidents: []
  },
  { 
    id: 'user-artist-1', 
    name: 'Kofi Mensah', 
    email: 'kofi@artellium.com', 
    role: 'artist', 
    password: 'artist123', 
    phone: '+233 24 123 4567', 
    country: 'Ghana', 
    subscription_tier: 'premium',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-05T12:00:00Z',
    lastActive: '2026-02-22T15:45:00Z',
    cloudflareVerified: true,
    ipAddress: '154.160.1.20',
    payoutBank: 'Standard Chartered Ghana',
    payoutAccount: '01002345678',
    securityIncidents: []
  },
  { 
    id: 'user-artist-2', 
    name: 'Amina Diallo', 
    email: 'amina@artellium.com', 
    role: 'artist', 
    password: 'artist123', 
    phone: '+234 802 987 6543', 
    country: 'Nigeria', 
    subscription_tier: 'premium',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-08T09:30:00Z',
    lastActive: '2026-02-22T16:50:00Z',
    cloudflareVerified: true,
    ipAddress: '105.112.98.5',
    payoutBank: 'Access Bank PLC',
    payoutAccount: '0234567891',
    securityIncidents: []
  },
  { 
    id: 'user-artist-3', 
    name: 'Tariq Ndebele', 
    email: 'tariq@artellium.com', 
    role: 'artist', 
    password: 'artist123', 
    phone: '+27 82 123 4567', 
    country: 'South Africa', 
    subscription_tier: 'standard',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-10T16:00:00Z',
    lastActive: '2026-02-21T09:15:00Z',
    cloudflareVerified: true,
    ipAddress: '197.229.0.14',
    payoutBank: 'First National Bank SA',
    payoutAccount: '62012345678',
    securityIncidents: []
  },
  { 
    id: 'user-artist-4', 
    name: 'Chief Bakare Ogundele', 
    email: 'bakare@artellium.com', 
    role: 'artist', 
    password: 'artist123', 
    phone: '+234 805 111 2233', 
    country: 'Nigeria', 
    subscription_tier: 'premium',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-02T11:15:00Z',
    lastActive: '2026-02-22T13:40:00Z',
    cloudflareVerified: true,
    ipAddress: '105.112.33.19',
    payoutBank: 'Zenith Bank PLC',
    payoutAccount: '1012345678',
    securityIncidents: []
  },
  { 
    id: 'user-artist-5', 
    name: 'Zola Okafor', 
    email: 'zola@artellium.com', 
    role: 'artist', 
    password: 'artist123', 
    phone: '+234 807 444 5566', 
    country: 'Nigeria', 
    subscription_tier: 'standard',
    status: 'active',
    statusReason: '',
    created_at: '2026-01-18T15:00:00Z',
    lastActive: '2026-02-22T14:10:00Z',
    cloudflareVerified: true,
    ipAddress: '102.89.88.2',
    payoutBank: 'Guaranty Trust Bank',
    payoutAccount: '0123987654',
    securityIncidents: []
  }
];

export const INITIAL_SELLERS = [
  { id: 'artist-1', user_id: 'user-artist-1', name: 'Kofi Mensah', bio: 'Master Painter & 24k Gold Leaf Specialist', country: 'Ghana', city: 'Accra', country_flag: '🇬🇭', avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300', tier: 'Premium', verification_badge: 'gold', studio_notes: 'My studio in Accra is filled with ancestral masks and bowls of gold dust.', payout_account_name: 'Kofi Mensah Fine Arts Enterprise', payout_bank: 'Standard Chartered Ghana', payout_account: '01002345678', commission_rate: 0.15 },
  { id: 'artist-2', user_id: 'user-artist-2', name: 'Amina Diallo', bio: 'Bronze Sculptor & Lost-Wax Heritage Preserver', country: 'Nigeria', city: 'Benin City', country_flag: '🇳🇬', avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300', tier: 'Premium', verification_badge: 'heritage', studio_notes: 'I work beside the same foundry fire my great-grandmother lit.', payout_account_name: 'Amina Diallo Bronze Foundry Ltd', payout_bank: 'Access Bank PLC', payout_account: '0234567891', commission_rate: 0.15 },
  { id: 'artist-3', user_id: 'user-artist-3', name: 'Tariq Ndebele', bio: 'Fine Artist & Soil Pigment Explorer', country: 'South Africa', city: 'Johannesburg', country_flag: '🇿🇦', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300', tier: 'Standard', verification_badge: 'verified', studio_notes: 'I collect soil, ash, and plant matter from across southern Africa and grind them into pigment.', payout_account_name: 'Tariq Ndebele Studio', payout_bank: 'First National Bank SA', payout_account: '62012345678', commission_rate: 0.15 },
  { id: 'artist-4', user_id: 'user-artist-4', name: 'Chief Bakare Ogundele', bio: 'Master Wood Carver & Sacred Yoruba Guild Elder', country: 'Nigeria', city: 'Oyo', country_flag: '🇳🇬', avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300', tier: 'Premium', verification_badge: 'gold', studio_notes: 'I was initiated into carving by my father at age nine.', payout_account_name: 'Bakare Ogundele Guild Studio', payout_bank: 'Zenith Bank PLC', payout_account: '1012345678', commission_rate: 0.15 },
  { id: 'artist-5', user_id: 'user-artist-5', name: 'Zola Okafor', bio: 'Afrofuturist 3D Visualizer & Digital Concept Artist', country: 'Nigeria', city: 'Lagos', country_flag: '🇳🇬', avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300', tier: 'Standard', verification_badge: 'verified', studio_notes: 'I render in the dark — literally. Nsibidi symbols are my building blocks.', payout_account_name: 'Zola Okafor Digital Labs', payout_bank: 'Guaranty Trust Bank', payout_account: '0123987654', commission_rate: 0.15 }
];

export const INITIAL_ORDERS = [];

export const INITIAL_PAYMENTS = [];

export const INITIAL_COMMISSIONS = [];

export const INITIAL_HEADER_CONFIG = {
  topBarText: 'The Premier Pan-African & Global Fine Art Marketplace',
  topBarBadge: 'ARTELLIUM',
  announcementActive: true,
  brandName: 'ARTELLIUM',
  brandSubtitle: 'FINE ART & AUCTIONS',
  showLanguageSelector: true,
  showCurrencySelector: true,
  navLinks: [
    { id: 'nav-1', label: 'All Artworks', href: '/explore', isVisible: true, highlight: 'none' },
    { id: 'nav-2', label: 'Painters', href: '/explore?category=Painters', isVisible: true, highlight: 'none' },
    { id: 'nav-3', label: 'Sculpture Makers', href: '/explore?category=Sculpture Makers', isVisible: true, highlight: 'none' },
    { id: 'nav-4', label: 'Digital Art', href: '/explore?category=Digital Art', isVisible: true, highlight: 'none' },
    { id: 'nav-5', label: 'Live Auctions', href: '/auctions', isVisible: true, highlight: 'red', icon: 'Flame' },
    { id: 'nav-6', label: 'Virtual Exhibitions', href: '/exhibitions', isVisible: true, highlight: 'emerald', icon: 'Eye' },
    { id: 'nav-7', label: 'Artist Subscriptions', href: '/artist/register', isVisible: true, highlight: 'gold', icon: 'Award' },
  ]
};

export const INITIAL_HERO_CONFIG = {
  heroType: 'jumia_art_hero', // 'jumia_art_hero' is the traditionally-coded Pan-African Fine Art Marketplace hero
  brandName: 'ARTELLIUM',
  badgeText: 'AFRICAN ROYALTY MEETS GLOBAL FINE ART COMMERCE',
  tagline: 'The future of African art is safe',
  voiceText: 'Welcome to Artellium. The future of African art is safe.',
  titleLine1: "The World's Premier",
  titleHighlight: 'Pan-African Fine Art',
  titleLine2: '& Auction House',
  description: 'Connecting elite African painters, bronze sculptors, and digital creators with global collectors, museums, and investors. Structured with verifiable provenance and direct Wema Bank corporate settlement.',
  mediaType: 'video', // 'video' or 'image'
  mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
  videoUrl: '', // empty by default so it shows the pure gold void unless video is set by admin
  videoPoster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
  videoAutoplay: true,
  videoMuted: true,
  videoLoop: true,
  videoOverlayOpacity: 0.65,
  featuredLot: {
    badge: 'LOT OF THE MONTH',
    title: 'The Ancestral Horizon',
    artist: 'Kofi Mensah (Ghana)',
    price: '₦1,850,000',
    medium: 'Oil & 24K Gold Leaf on Canvas',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
    artworkId: 'art-101',
    isVisible: true,
  },
  primaryCta: { label: 'Explore Catalog', href: '/explore', isVisible: true },
  secondaryCta: { label: 'Enter Live Auction', href: '/auctions', isVisible: true },
  tertiaryCta: { label: 'Artist Onboarding (₦30k - ₦50k/mo)', href: '/artist/register', isVisible: true },
  stats: [
    { id: 'stat-1', label: 'Fine Art Transacted', value: '₦4.5B+', color: 'gold' },
    { id: 'stat-2', label: 'Verified Masterpieces', value: '1,200+', color: 'white' },
    { id: 'stat-3', label: 'African Nations Represented', value: '54', color: 'emerald' },
  ],
  slides: [
    {
      id: 'slide-1',
      title: 'The Ancestral Horizon',
      artist: 'Kofi Mensah',
      country: 'Ghana',
      mediaType: 'image',
      mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
      price: 1850000,
      badge: 'Featured Masterpiece'
    },
    {
      id: 'slide-2',
      title: 'Warrior of the Bronze Empire',
      artist: 'Amina Diallo',
      country: 'Nigeria',
      mediaType: 'image',
      mediaUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000',
      price: 3200000,
      badge: 'Live Auction Spotlight'
    }
  ]
};

export const INITIAL_HOMEPAGE_CONFIG = {
  sections: [
    { id: 'sec-hero', type: 'hero', title: 'Hero Section', isVisible: true },
    { id: 'sec-categories', type: 'categories', title: 'Category Filter Bar', isVisible: true },
    { 
      id: 'sec-auctions', 
      type: 'auctions', 
      title: 'Live Fine Art Auctions', 
      subtitle: 'Participate in real-time competitive bidding for high-value African masterworks.', 
      badge: 'LIVE BIDDING ARENA', 
      isVisible: true,
      maxItems: 3
    },
    { 
      id: 'sec-newly-listed', 
      type: 'newly_listed', 
      title: 'Newly Listed Artworks', 
      subtitle: 'Fresh creations uploaded directly by verified master painters, sculptors, and digital artists.', 
      badge: 'CURATED MARKETPLACE', 
      isVisible: true,
      maxItems: 9
    },
    { 
      id: 'sec-subscriptions', 
      type: 'subscriptions', 
      title: 'Showcase Your Fine Art with Zero Hindrance', 
      subtitle: 'Join ARTELLIUM as a verified seller. Upload original oil paintings, bronze sculptures, or digital prints with automated backend tracking and international buyer outreach.', 
      badge: 'ARTIST & SELLER SUBSCRIPTION PACKAGES', 
      isVisible: true 
    },
    { 
      id: 'sec-recently-sold', 
      type: 'recently_sold', 
      title: 'Recently Sold Masterpieces', 
      subtitle: 'Transactions logged in our immutable ledger of African creative heritage and authenticity registry.', 
      badge: 'HISTORICAL LEDGER & PROVENANCE', 
      isVisible: true,
      maxItems: 3
    },
    { 
      id: 'sec-exhibitions', 
      type: 'exhibitions', 
      title: 'Current Exhibitions', 
      subtitle: 'Explore curated virtual gallery halls from top African museum directors and curators.', 
      badge: 'VIRTUAL GALLERY ROOMS', 
      isVisible: true,
      maxItems: 4
    }
  ],
  customPromoBanners: [
    {
      id: 'promo-1',
      title: 'Pan-African Fine Art Biennale 2026',
      subtitle: 'Exclusive private viewings, museum-grade certificates, and verified provenance for elite collectors.',
      tag: 'CURATORIAL SPOTLIGHT',
      buttonText: 'Explore Biennale Collection',
      buttonLink: '/explore',
      bgGradient: 'from-amber-950 via-slate-900 to-black',
      borderColor: 'border-art-gold/40',
      isVisible: true
    }
  ]
};

export const INITIAL_FOOTER_CONFIG = {
  brandTitle: 'ARTELLIUM',
  brandDescription: 'ARTELLIUM bridges ancient African artistic royalty with cutting-edge global fine art commerce. Empowering painters, sculptors, and digital creators through transparent auctions and authentic gallery exhibitions.',
  newsletterTitle: 'Join collector newsletter...',
  newsletterButtonText: 'Join',
  copyrightNotice: '© {year} ARTELLIUM AFRICA & GLOBAL MARKETPLACE. All rights reserved.',
  bottomSubtext: 'Crafted with cultural pride & global excellence for African Master Creators.',
  trustBadges: [
    {
      id: 'badge-1',
      title: 'Authenticity Guarantee',
      description: 'Physical certificate signed by artist & curator.',
      icon: 'Award',
      color: 'gold',
      isVisible: true
    },
    {
      id: 'badge-2',
      title: 'Curatorial Excellence',
      description: 'Accredited provenance & authentic gallery exhibitions.',
      icon: 'Shield',
      color: 'emerald',
      isVisible: true
    },
    {
      id: 'badge-3',
      title: 'Wema Bank Secured Settlement',
      description: 'Direct corporate banking & instant payment settlement.',
      icon: 'Lock',
      color: 'gold',
      isVisible: true
    },
    {
      id: 'badge-4',
      title: 'Master Artist Support',
      description: 'Directly empowering pan-African talent.',
      icon: 'Shield',
      color: 'gold',
      isVisible: true
    }
  ],
  columns: [
    {
      id: 'col-1',
      title: 'About Us',
      links: [
        { id: 'link-c1-1', label: 'Artellium Goal', href: '/about#goal', isVisible: true, highlight: 'gold' },
        { id: 'link-c1-2', label: 'Who We Are', href: '/about#who-we-are', isVisible: true },
        { id: 'link-c1-3', label: 'Our Vision', href: '/about#vision', isVisible: true },
        { id: 'link-c1-4', label: 'Our Mission', href: '/about#mission', isVisible: true },
        { id: 'link-c1-5', label: 'Our Core Values', href: '/about#core-values', isVisible: true }
      ]
    },
    {
      id: 'col-2',
      title: 'Policies',
      links: [
        { id: 'link-c2-1', label: 'Terms of Provenance & Authenticity', href: '/policies#provenance', isVisible: true },
        { id: 'link-c2-2', label: 'Wema Bank Direct Banking & Settlement', href: '/policies#wema-banking', isVisible: true },
        { id: 'link-c2-3', label: 'Authenticity Guarantee & Consignment', href: '/policies#consignment', isVisible: true },
        { id: 'link-c2-4', label: 'Direct Bank Refunds & Disputes', href: '/policies#refunds', isVisible: true, highlight: 'emerald' },
        { id: 'link-c2-5', label: 'Privacy & Financial Data Security', href: '/policies#privacy', isVisible: true },
        { id: 'link-c2-6', label: 'Artist & Seller Code of Conduct', href: '/policies#seller-conduct', isVisible: true }
      ]
    },
    {
      id: 'col-3',
      title: 'Contact Us',
      links: [
        { id: 'link-c3-1', label: 'Email: support@artellium.com', href: 'mailto:support@artellium.com', isVisible: true, highlight: 'gold' },
        { id: 'link-c3-2', label: 'Phone: +234 1 888 2783', href: 'tel:+23418882783', isVisible: true },
        { id: 'link-c3-3', label: 'WhatsApp: +234 800 000 2783', href: 'https://wa.me/2348000002783', isVisible: true },
        { id: 'link-c3-4', label: 'Our Gallery Locations', href: '/contact#locations', isVisible: true },
        { id: 'link-c3-5', label: 'Send Us a Message', href: '/contact', isVisible: true, highlight: 'emerald' }
      ]
    }
  ],
  socialLinks: [
    { id: 'soc-1', platform: 'Instagram', url: 'https://instagram.com', isVisible: true },
    { id: 'soc-2', platform: 'Twitter / X', url: 'https://x.com', isVisible: true },
    { id: 'soc-3', platform: 'LinkedIn', url: 'https://linkedin.com', isVisible: true },
    { id: 'soc-4', platform: 'YouTube', url: 'https://youtube.com', isVisible: true }
  ]
};

// =========================================================================
// PAN-AFRICAN MULTI-CURRENCY & REGIONAL HUBS CONFIGURATION
// =========================================================================
export const PAN_AFRICAN_CURRENCIES = {
  NGN: { code: 'NGN', symbol: '₦', rate: 1, name: 'Nigerian Naira (₦)', flag: '🇳🇬', country: 'Nigeria' },
  USD: { code: 'USD', symbol: '$', rate: 1 / 1480, name: 'US Dollar ($)', flag: '🌐', country: 'International' },
  GHS: { code: 'GHS', symbol: 'GH₵', rate: 1 / 95, name: 'Ghanaian Cedi (GH₵)', flag: '🇬🇭', country: 'Ghana' },
  ZAR: { code: 'ZAR', symbol: 'R', rate: 1 / 80, name: 'South African Rand (R)', flag: '🇿🇦', country: 'South Africa' },
  KES: { code: 'KES', symbol: 'KSh', rate: 1 / 11.5, name: 'Kenyan Shilling (KSh)', flag: '🇰🇪', country: 'Kenya' },
  MAD: { code: 'MAD', symbol: 'MAD ', rate: 1 / 145, name: 'Moroccan Dirham (MAD)', flag: '🇲🇦', country: 'Morocco' },
  EGP: { code: 'EGP', symbol: 'E£', rate: 1 / 30, name: 'Egyptian Pound (E£)', flag: '🇪🇬', country: 'Egypt' },
  XOF: { code: 'XOF', symbol: 'CFA ', rate: 1 / 2.4, name: 'West African CFA (CFA)', flag: '🌍', country: 'UEMOA Region' }
};

export const PAN_AFRICAN_REGIONS = [
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', hub: 'Lagos Headquarters', currency: 'NGN', status: 'Active (HQ)', taxRate: 7.5, artistsCount: 42, activeCollectors: 1240 },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', hub: 'Accra Curatorial Bureau', currency: 'GHS', status: 'Active (Direct)', taxRate: 15.0, artistsCount: 18, activeCollectors: 480 },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', hub: 'Johannesburg Regional Bureau', currency: 'ZAR', status: 'Active (Direct)', taxRate: 15.0, artistsCount: 22, activeCollectors: 610 },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', hub: 'Nairobi East Africa Desk', currency: 'KES', status: 'Active (Direct)', taxRate: 16.0, artistsCount: 14, activeCollectors: 350 },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', hub: 'Marrakech Atelier Desk', currency: 'MAD', status: 'Active (Direct)', taxRate: 20.0, artistsCount: 12, activeCollectors: 290 },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', hub: 'Cairo Nile Gallery', currency: 'EGP', status: 'Active (Direct)', taxRate: 14.0, artistsCount: 9, activeCollectors: 210 },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', hub: 'Kigali Cultural Hub', currency: 'USD', status: 'Active (Direct)', taxRate: 18.0, artistsCount: 7, activeCollectors: 130 },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', hub: 'Dakar Biennale Bureau', currency: 'XOF', status: 'Active (Direct)', taxRate: 18.0, artistsCount: 11, activeCollectors: 190 },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', hub: 'Abidjan Arts Center', currency: 'XOF', status: 'Active (Direct)', taxRate: 18.0, artistsCount: 8, activeCollectors: 140 }
];

// =========================================================================
// INITIAL FLASH DEALS
// =========================================================================
export const INITIAL_FLASH_DEALS = [
  {
    id: 'fd-101',
    artworkId: 'art-107',
    title: 'Spirit of the Mask',
    artistName: 'Chief Bakare Ogundele',
    artistId: 'artist-4',
    country: 'Nigeria 🇳🇬',
    category: 'Sculpture Makers',
    medium: 'Carved Iroko Wood & Brass Inlay',
    originalPrice: 1950000,
    discountedPrice: 1450000,
    discountPercent: 25,
    availableUnits: 1,
    claimedPercent: 75,
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&q=80&w=1000',
    description: 'Sacred Yoruba ceremonial carving with hand-hammered brass inlay, offering exceptional presence and cultural lineage.',
    status: 'active',
    endsAt: Date.now() + 1000 * 60 * 60 * 6 + 1000 * 60 * 12
  },
  {
    id: 'fd-102',
    artworkId: 'art-109',
    title: 'Children of the Sun',
    artistName: 'Kenza Belghiti',
    artistId: 'artist-5',
    country: 'Morocco 🇲🇦',
    category: 'Painters',
    medium: 'Acrylic & Gold Dust on Canvas',
    originalPrice: 2100000,
    discountedPrice: 1680000,
    discountPercent: 20,
    availableUnits: 2,
    claimedPercent: 60,
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1000',
    description: 'Atmospheric North African portraiture exploring light and Berber heritage with authentic 22K gold dust accents.',
    status: 'active',
    endsAt: Date.now() + 1000 * 60 * 60 * 6 + 1000 * 60 * 12
  },
  {
    id: 'fd-103',
    artworkId: 'art-110',
    title: 'Ancestral Geometry',
    artistName: 'Chidi Nwosu',
    artistId: 'artist-6',
    country: 'Nigeria 🇳🇬',
    category: 'Painters',
    medium: 'Mixed Media & Natural Pigments',
    originalPrice: 620000,
    discountedPrice: 465000,
    discountPercent: 25,
    availableUnits: 3,
    claimedPercent: 70,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=1000',
    description: 'Intricate Uli-inspired geometric expressions utilizing organic riverbed minerals and raw linen.',
    status: 'active',
    endsAt: Date.now() + 1000 * 60 * 60 * 6 + 1000 * 60 * 12
  }
];

// =========================================================================
// INITIAL ROYAL HEIRLOOMS & PRIVATE INQUIRIES
// =========================================================================
export const INITIAL_ROYAL_HEIRLOOMS = [
  {
    id: 'art-royal-1',
    title: 'Queen Idia Commemorative Bronze Mask',
    artistName: 'Guild of Royal Igun Bronzecasters',
    dynasty: 'Kingdom of Benin (16th Century Lineage Revival)',
    epoch: '16th Century Lineage',
    category: 'Imperial Bronzes',
    medium: 'Hand-Poured Cast Bronze, 24K Gold Inlay & Coral Beads',
    dimensions: '52 × 28 × 18 cm',
    valuation: 14500000,
    provenanceHash: 'ROYAL-BEN-IDIA-88942-CERT',
    status: 'Available for Private Treaty',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000',
    description: 'An extraordinary royal commemorative masterpiece created by direct descendants of the court casters of Benin.',
    authenticity: 'Certified by Pan-African Royal Heritage Registry · Dual Physical Hologram Sealed'
  },
  {
    id: 'art-royal-2',
    title: 'The Golden Stool Regalia Pendant',
    artistName: 'Ashanti Court Goldsmiths',
    dynasty: 'Ashanti Empire (Kumasi, Ghana)',
    epoch: 'Imperial Ashanti Epoch',
    category: 'Royal Goldwork',
    medium: 'Solid 22K African Gold & Carved Sacred Cedar',
    dimensions: '40 × 30 × 12 cm',
    valuation: 18200000,
    provenanceHash: 'ROYAL-ASH-GOLD-99120-CERT',
    status: 'Vault Custody Reserved',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
    description: 'Sacred ceremonial gold repoussé honoring the Golden Stool (Sika Dwa Kofi).',
    authenticity: 'Kumasi Cultural Centre Certified · Vault Physical Ledger Verified'
  }
];

export const INITIAL_ROYAL_INQUIRIES = [];

// =========================================================================
// INITIAL CURATOR PICKS
// =========================================================================
export const INITIAL_CURATOR_PICKS = [
  {
    id: 'cp-101',
    artworkId: 'art-101',
    title: 'The Ancestral Horizon',
    artistName: 'Kofi Mensah',
    country: 'Ghana 🇬🇭',
    category: 'Painters',
    medium: 'Oil & 24K Gold Leaf on Canvas',
    price: 1850000,
    curatorName: 'Dr. Nana Osei',
    curatorRole: 'Director of Contemporary African Art, Accra Art Trust',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1000',
    curatorCritique: 'Kofi Mensah has achieved an uncommon equilibrium between ancient Akan metaphysical heritage and monumental contemporary abstraction.',
    exhibitionHall: 'West African Modernism Pavilion',
    status: 'published'
  },
  {
    id: 'cp-102',
    artworkId: 'art-102',
    title: 'Warrior of the Bronze Empire',
    artistName: 'Amina Diallo',
    country: 'Nigeria 🇳🇬',
    category: 'Sculpture Makers',
    medium: 'Cast Bronze & Ebony Wood Base',
    price: 3200000,
    curatorName: 'Prof. Folake Adeleke',
    curatorRole: 'Senior Fellow in African Metallurgy, Royal Heritage Foundation',
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=1000',
    curatorCritique: 'Diallo’s bronze bust resurrects the immortal gravitas of 16th-century Benin foundry artistry while challenging classical patriarchal forms.',
    exhibitionHall: 'Imperial Bronzes & Metallurgical Heritage',
    status: 'published'
  }
];

// =========================================================================
// INITIAL PROVENANCE LEDGER BLOCKS
// =========================================================================
export const INITIAL_LEDGER_BLOCKS = [
  {
    id: 'PL-2026-88914',
    blockHeight: '#008942',
    timestamp: '2026-02-14 18:42:10 UTC',
    artworkTitle: 'The Ancestral Horizon (Atelier Proof No. 1)',
    artistName: 'Kofi Mensah (Ghana)',
    medium: 'Oil & 24K Gold Leaf on Linen',
    settlementPrice: 1850000,
    custodian: 'Dr. Evelyn Carter (London, UK)',
    settlementBank: 'Wema Bank PLC / Dual Fiduciary Settlement',
    provenanceHash: '0x8f7a9d32b410c8e192f039a48d1c7205e4b99812',
    physicalCertificateId: 'ART-CERT-GH-88914-SEALED',
    status: 'Vault Verified & Transferred',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'PL-2026-77319',
    blockHeight: '#008941',
    timestamp: '2026-02-11 12:15:33 UTC',
    artworkTitle: 'Warrior of the Bronze Empire (Study Lot)',
    artistName: 'Amina Diallo (Benin City, Nigeria)',
    medium: 'Cast Bronze & Ebony Base',
    settlementPrice: 3400000,
    custodian: 'Chief T. Adeleke (Lagos, Nigeria)',
    settlementBank: 'Access Bank Fiduciary Vault',
    provenanceHash: '0x3c99e1208fb4201a4e76c118749a0d819fa62031',
    physicalCertificateId: 'ART-CERT-NG-77319-SEALED',
    status: 'Vault Verified & Transferred',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=600'
  }
];

// =========================================================================
// INITIAL ARTIST VERIFICATION DOSSIERS
// =========================================================================
export const INITIAL_ARTIST_VERIFICATIONS = [
  {
    id: 'verif-1',
    artistId: 'artist-1',
    artistName: 'Kofi Mensah',
    country: 'Ghana',
    flag: '🇬🇭',
    badge: 'gold',
    badgeLabel: 'Gold Crest Certified',
    kycHash: 'VERIF-GH-KM-2026-GOLD',
    accreditation: 'National Museum of Ghana Fellow · 25+ Years Atelier Master',
    status: 'approved',
    reviewedBy: 'Executive Board',
    approvalDate: '2026-01-15'
  },
  {
    id: 'verif-2',
    artistId: 'artist-2',
    artistName: 'Amina Diallo',
    country: 'Nigeria',
    flag: '🇳🇬',
    badge: 'heritage',
    badgeLabel: 'Heritage Master Certified',
    kycHash: 'VERIF-NG-AD-88410-HERIT',
    accreditation: 'Royal Guild of Bronzecasters Lineage · Master of Lost-Wax Casting',
    status: 'approved',
    reviewedBy: 'Executive Board',
    approvalDate: '2026-01-20'
  }
];


